services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/php_wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    env_file:
      - .env
    environment:
      - DB_HOST=mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx_proxy
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/liliu/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/liliu/data/wordpress

networks:
  inception:
    driver: bridge
